apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1  # Nombre de réplicas souhaitées
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: 23153122e351/teeeeeeeeeest:v1
        ports:
        - containerPort: 80  # Port sur lequel le conteneur écoute
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front  # Sélectionne les pods avec le label "app: front"
  ports:
  - protocol: TCP
    port: 80  # Port du service
    targetPort: 80  # Port sur lequel les pods du déploiement écoute
    nodePort: 30685  # Port NodePort
  type: NodePort  # Type de service (ClusterIP, NodePort, LoadBalancer, etc.)
